apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: lab
spec:
  selector:
    app: app2-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
